# Generated by Django 3.2 on 2023-02-19 18:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(10, message='Sorry, but you cannot assign rating higher then 10.'), django.core.validators.MinValueValidator(1, message='Sorry, but you cannot assign rating lower then 1')], verbose_name='Оценка'),
        ),
    ]
